#!/bin/bash
if [[$1]]
then
  /usr/bin/tor -f /etc/tor/torrc --runasdaemon $1
  echo "starting tor services"
else
  /usr/bin/tor -f /etc/tor/torrc --runasdaemon 1
  echo "starting tor services as daemon"
fi