services:
  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile.custom
    container_name: tor
    networks:
       - tor-bridge

  hidden_room:
    build: .
    container_name: web
    network_mode: service:tor

networks:
  tor-bridge: